### ISSUE TITLE
complete newb looking for advice

### ISSUE THREAD

**Issue by stew9021** [taeukme/google-home-push#18]
Hi, sorry if this isnt the best way to get in touch but I couldnt see another obvious way. I have had an idea and I think this project could really help, essentially I have a large button that my dog pushes to signal that he wants me to open the back door, problem is I cant hear it from most of the house. My idea is that I would get a rasbery pi and use some code like yours to make it send a voice command "jax wants the door open" to all of the google home speakers in my house. Do you think this would be possible? just looking for some high level advice before I buy a pi and start learning the basics of Java etc 
thanks

Stewart

**Comment by taeukkang** [comment]
Hey Stewart,

I apologize for the delayed response, but yes, it would be achievable. Connect the button to the Raspberry Pi, detect the button's signal with Node.js, and have it make the TTS request with this library.

Cheers,
Taeuk
