### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by kiai72** [taeukme/google-home-push#6]
after getting this error:
make: Entering directory '/home/pi/google-home-push-master/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
                    ^
compilation terminated.

i tried npm i google-home-push again - but this time i get this error:
pi@retropie:~/google-home-push-master $ npm i google-home-push
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "google-home-push" under a package
npm ERR! also called "google-home-push". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-01-22T17_29_07_120Z-debug.log

it's raspbian stretch 4.4

**Comment by Jack-Drake** [comment]
Try running this command:

sudo apt-get install libavahi-compat-libdnssd-dev
