### ISSUE TITLE
Google Cast Client Error: read ECONNRESET

### ISSUE THREAD

**Issue by Jack-Drake** [taeukme/google-home-push#8]
When I run a test of just saying hello on google home it works inside my network but when outside such as from my outside ip address I get this error.

`(node:17592) UnhandledPromiseRejectionWarning: Google Cast Client error:
Error: read ECONNRESET
(node:17592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Google Cast Client error:
Error: read ECONNRESET
`

What could have caused this error?

**Comment by mduzgun** [comment]
@yahyaisfast Can you find any solution for this problem. When outside of local wifi network, I can't reach my google home using IP address. 

(node:3984) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Google Cast Client error:
Error: connect ETIMEDOUT 10.100..........:8009
(node:3984) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Google Cast Client error:
Error: connect ETIMEDOUT 10.100..........:8009
