### ISSUE TITLE
install error for windows 10

### ISSUE THREAD

**Issue by mduzgun** [taeukme/google-home-push#9]
C:\Users\mehmetdu\google-home-push\node_modules\mdns\build\dns_sd_bindings.vcxproj(24,3): error MSB4019: The imported p roject "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, an d that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\mehmetdu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mehmetdu\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mehmetdu\google-home-push\node_modules\mdns
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mehmetdu\AppData\Roaming\npm-cache\_logs\2019-06-12T13_59_55_579Z-debug.log

how to fix this problem?

**Comment by taeukkang** [comment]
Fixed https://github.com/taeukme/google-home-push/commit/10091b719c653e2278757a514b005ba19e49b067
